### ISSUE TITLE
Release model outside of weiyun

### ISSUE THREAD

**Issue by bdnkth** [kylekma/X2CT#10]
Hi there,

I'm really interested in your work, especially in your models. However, accessing weiyun is not so easy in my country. Can you please release the model files either in github or in google cloud? Or upload the model files on wetransfer and send me a link?
I would really appreciate if you could help me out accessing your promising research work.

**Comment by joachimckh** [comment]
I second this, it would be nice to test the model.

**Comment by KetCathy** [comment]
> Hi there,
> 
> I'm really interested in your work, especially in your models. However, accessing weiyun is not so easy in my country. Can you please release the model files either in github or in google cloud? Or upload the model files on wetransfer and send me a link?
> I would really appreciate if you could help me out accessing your promising research work.

Did you manage to get the models?? I would like to access them too. Thanks

**Comment by joachimckh** [comment]
I still haven't got access to them, but I'm also still very interested in this work.

**Comment by kylekma** [comment]
Dear all, 
We upload a copy of the trained model to dropbox, please see the link https://www.dropbox.com/sh/06r3g02dyeyh5x5/AADFhwRuG_SPuGGwKx-SZLrna?dl=0

**Comment by sainatarajan** [comment]
@kylekma Thank you. If possible, can you upload the preprocessed dataset to dropbox as well? I see that it's only uploaded to weiyun. Or else, could you explain the structure of the dataset? I see that in the readme, there's a data folder, but the structure of the .h5 files and the text files are not clear.

**Comment by Wapity** [comment]
+1 an explanation or data directly would be good thank you

**Comment by mohammadnabeel** [comment]
I tried to test the model, but it gives me `AssertionError: Path do not exist: ./data/LIDC-HDF5-256\LIDC-IDRI-0003.20000101.3000611.1\ct_xray_data.h5`

I think I've to download the **70GB file**! which I couldn't from my country!
it will be great if they can kindly upload it to dropbox as well...
